version: "3.2"

services:
  backend:
    image: commune/luca/bittensor/backend
    container_name: luca-bittensor-backend
    build: ./
    # entrypoint: ["gunicorn", "--worker-class", "eventlet", "-w", "1", "-b", "0.0.0.0:5000", "--preload", "server.app:app"]
    
    environment:
      - LOCAL_SUBTENSOR_HOST=subtensor
    ports:
      # - 5000:5000
      # - 8501-8505:8501-8505
      # - 8080:8080 #  
      - 7865-7870:7865-7870 # gradio ports
      - 8000:8000 # api


    volumes:
      - ./bittensor/bittensor:/app/bittensor/bittensor
      - ./commune:/app/commune
      - ./.bittensor:/root/.bittensor
      - ./scripts:/app/scripts


    deploy:
      resources:
         reservations:
           devices:
           - driver: nvidia
             count: 'all'
             capabilities: [gpu]

    command: bash -c "cd /app; chmod +x /app/scripts/*;/app/scripts/startup.sh;"

  