# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commune.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='commune.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rcommune.proto\"D\n\x0eSignatureBlock\x12\x11\n\tpublickey\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x0c\n\x04type\x18\x03 \x01(\t\"O\n\tDataBlock\x12\"\n\tsignature\x18\x01 \x01(\x0b\x32\x0f.SignatureBlock\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08metadata\x18\x03 \x01(\x0c\x32.\n\x07\x43ommune\x12#\n\x07\x46orward\x12\n.DataBlock\x1a\n.DataBlock\"\x00\x62\x06proto3'
)




_SIGNATUREBLOCK = _descriptor.Descriptor(
  name='SignatureBlock',
  full_name='SignatureBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publickey', full_name='SignatureBlock.publickey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='SignatureBlock.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='SignatureBlock.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=85,
)


_DATABLOCK = _descriptor.Descriptor(
  name='DataBlock',
  full_name='DataBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='DataBlock.signature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='DataBlock.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='DataBlock.metadata', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=166,
)

_DATABLOCK.fields_by_name['signature'].message_type = _SIGNATUREBLOCK
DESCRIPTOR.message_types_by_name['SignatureBlock'] = _SIGNATUREBLOCK
DESCRIPTOR.message_types_by_name['DataBlock'] = _DATABLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignatureBlock = _reflection.GeneratedProtocolMessageType('SignatureBlock', (_message.Message,), {
  'DESCRIPTOR' : _SIGNATUREBLOCK,
  '__module__' : 'commune_pb2'
  # @@protoc_insertion_point(class_scope:SignatureBlock)
  })
_sym_db.RegisterMessage(SignatureBlock)

DataBlock = _reflection.GeneratedProtocolMessageType('DataBlock', (_message.Message,), {
  'DESCRIPTOR' : _DATABLOCK,
  '__module__' : 'commune_pb2'
  # @@protoc_insertion_point(class_scope:DataBlock)
  })
_sym_db.RegisterMessage(DataBlock)



_COMMUNE = _descriptor.ServiceDescriptor(
  name='Commune',
  full_name='Commune',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=168,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='Forward',
    full_name='Commune.Forward',
    index=0,
    containing_service=None,
    input_type=_DATABLOCK,
    output_type=_DATABLOCK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMUNE)

DESCRIPTOR.services_by_name['Commune'] = _COMMUNE

# @@protoc_insertion_point(module_scope)
